### ISSUE TITLE
Confusing sentence, possible typo

### ISSUE THREAD

**Issue by jrhorn424** [ga-wdi-boston/wdi_1_ruby_demo_methods_recursion#1]
> Most computer langauges (such as Ruby, JavaScript and C) allow us to call a function from within itself. The use of this to solve a problem is called recursion and is a central idea in computer science. In functional programming it is frequently used instead of recursion, depending on the structure of the language.

The first "languages" is a typo. The last sentence: 

> The use of this to solve a problem is called **recursion** and is a central idea in computer science. In functional programming it is frequently used instead of **recursion**...

I think the second instance of recursion here was meant to be something else.

**Comment by tibbon** [comment]
second thing is intended to be iteration. Agreed on typo.
